// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: cef_service.proto

#include "cef_service.pb.h"
#include "cef_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace cefcontrol {

static const char* CefControlService_method_names[] = {
  "/cefcontrol.CefControlService/Handshake",
  "/cefcontrol.CefControlService/OpenPage",
  "/cefcontrol.CefControlService/PageStatus",
  "/cefcontrol.CefControlService/Shutdown",
};

std::unique_ptr< CefControlService::Stub> CefControlService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CefControlService::Stub> stub(new CefControlService::Stub(channel, options));
  return stub;
}

CefControlService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Handshake_(CefControlService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OpenPage_(CefControlService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PageStatus_(CefControlService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Shutdown_(CefControlService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CefControlService::Stub::Handshake(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest& request, ::cefcontrol::HandshakeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::cefcontrol::HandshakeRequest, ::cefcontrol::HandshakeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Handshake_, context, request, response);
}

void CefControlService::Stub::async::Handshake(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest* request, ::cefcontrol::HandshakeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::cefcontrol::HandshakeRequest, ::cefcontrol::HandshakeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Handshake_, context, request, response, std::move(f));
}

void CefControlService::Stub::async::Handshake(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest* request, ::cefcontrol::HandshakeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Handshake_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::cefcontrol::HandshakeResponse>* CefControlService::Stub::PrepareAsyncHandshakeRaw(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::cefcontrol::HandshakeResponse, ::cefcontrol::HandshakeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Handshake_, context, request);
}

::grpc::ClientAsyncResponseReader< ::cefcontrol::HandshakeResponse>* CefControlService::Stub::AsyncHandshakeRaw(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandshakeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CefControlService::Stub::OpenPage(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest& request, ::cefcontrol::OpenPageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::cefcontrol::OpenPageRequest, ::cefcontrol::OpenPageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OpenPage_, context, request, response);
}

void CefControlService::Stub::async::OpenPage(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest* request, ::cefcontrol::OpenPageResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::cefcontrol::OpenPageRequest, ::cefcontrol::OpenPageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OpenPage_, context, request, response, std::move(f));
}

void CefControlService::Stub::async::OpenPage(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest* request, ::cefcontrol::OpenPageResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OpenPage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::cefcontrol::OpenPageResponse>* CefControlService::Stub::PrepareAsyncOpenPageRaw(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::cefcontrol::OpenPageResponse, ::cefcontrol::OpenPageRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OpenPage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::cefcontrol::OpenPageResponse>* CefControlService::Stub::AsyncOpenPageRaw(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOpenPageRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CefControlService::Stub::PageStatus(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest& request, ::cefcontrol::PageStatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::cefcontrol::PageStatusRequest, ::cefcontrol::PageStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PageStatus_, context, request, response);
}

void CefControlService::Stub::async::PageStatus(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest* request, ::cefcontrol::PageStatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::cefcontrol::PageStatusRequest, ::cefcontrol::PageStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PageStatus_, context, request, response, std::move(f));
}

void CefControlService::Stub::async::PageStatus(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest* request, ::cefcontrol::PageStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PageStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::cefcontrol::PageStatusResponse>* CefControlService::Stub::PrepareAsyncPageStatusRaw(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::cefcontrol::PageStatusResponse, ::cefcontrol::PageStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PageStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::cefcontrol::PageStatusResponse>* CefControlService::Stub::AsyncPageStatusRaw(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPageStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CefControlService::Stub::Shutdown(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest& request, ::cefcontrol::ShutdownResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::cefcontrol::ShutdownRequest, ::cefcontrol::ShutdownResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Shutdown_, context, request, response);
}

void CefControlService::Stub::async::Shutdown(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest* request, ::cefcontrol::ShutdownResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::cefcontrol::ShutdownRequest, ::cefcontrol::ShutdownResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Shutdown_, context, request, response, std::move(f));
}

void CefControlService::Stub::async::Shutdown(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest* request, ::cefcontrol::ShutdownResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Shutdown_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::cefcontrol::ShutdownResponse>* CefControlService::Stub::PrepareAsyncShutdownRaw(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::cefcontrol::ShutdownResponse, ::cefcontrol::ShutdownRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Shutdown_, context, request);
}

::grpc::ClientAsyncResponseReader< ::cefcontrol::ShutdownResponse>* CefControlService::Stub::AsyncShutdownRaw(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncShutdownRaw(context, request, cq);
  result->StartCall();
  return result;
}

CefControlService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CefControlService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CefControlService::Service, ::cefcontrol::HandshakeRequest, ::cefcontrol::HandshakeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CefControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::cefcontrol::HandshakeRequest* req,
             ::cefcontrol::HandshakeResponse* resp) {
               return service->Handshake(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CefControlService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CefControlService::Service, ::cefcontrol::OpenPageRequest, ::cefcontrol::OpenPageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CefControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::cefcontrol::OpenPageRequest* req,
             ::cefcontrol::OpenPageResponse* resp) {
               return service->OpenPage(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CefControlService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CefControlService::Service, ::cefcontrol::PageStatusRequest, ::cefcontrol::PageStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CefControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::cefcontrol::PageStatusRequest* req,
             ::cefcontrol::PageStatusResponse* resp) {
               return service->PageStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CefControlService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CefControlService::Service, ::cefcontrol::ShutdownRequest, ::cefcontrol::ShutdownResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CefControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::cefcontrol::ShutdownRequest* req,
             ::cefcontrol::ShutdownResponse* resp) {
               return service->Shutdown(ctx, req, resp);
             }, this)));
}

CefControlService::Service::~Service() {
}

::grpc::Status CefControlService::Service::Handshake(::grpc::ServerContext* context, const ::cefcontrol::HandshakeRequest* request, ::cefcontrol::HandshakeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CefControlService::Service::OpenPage(::grpc::ServerContext* context, const ::cefcontrol::OpenPageRequest* request, ::cefcontrol::OpenPageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CefControlService::Service::PageStatus(::grpc::ServerContext* context, const ::cefcontrol::PageStatusRequest* request, ::cefcontrol::PageStatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CefControlService::Service::Shutdown(::grpc::ServerContext* context, const ::cefcontrol::ShutdownRequest* request, ::cefcontrol::ShutdownResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace cefcontrol

