// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: cef_service.proto
#ifndef GRPC_cef_5fservice_2eproto__INCLUDED
#define GRPC_cef_5fservice_2eproto__INCLUDED

#include "cef_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace cefcontrol {

// *
// Phase-6 gRPC Service
//
// Single unary RPC per command type.
// CEF is client. Java is server.
//
// All methods are unary (request ? response).
// No streaming, no bidirectional communication at gRPC level.
//
// Phase-7 TODO: Consider adding streaming for high-frequency events (metrics, logs).
class CefControlService final {
 public:
  static constexpr char const* service_full_name() {
    return "cefcontrol.CefControlService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // *
    // Handshake RPC.
    // CEF initiates this on connection.
    // Java validates and accepts/rejects the session.
    //
    // This MUST be the first RPC called by CEF.
    virtual ::grpc::Status Handshake(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest& request, ::cefcontrol::HandshakeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::HandshakeResponse>> AsyncHandshake(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::HandshakeResponse>>(AsyncHandshakeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::HandshakeResponse>> PrepareAsyncHandshake(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::HandshakeResponse>>(PrepareAsyncHandshakeRaw(context, request, cq));
    }
    // *
    // Open Page RPC.
    // Java sends OpenPageRequest.
    // CEF responds immediately with OpenPageResponse (accepted or rejected).
    //
    // CEF then asynchronously sends PageStatusNotification messages
    // (via a separate callback mechanism or polling).
    //
    // Phase-7 TODO: Implement notification delivery (polling or push).
    virtual ::grpc::Status OpenPage(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest& request, ::cefcontrol::OpenPageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::OpenPageResponse>> AsyncOpenPage(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::OpenPageResponse>>(AsyncOpenPageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::OpenPageResponse>> PrepareAsyncOpenPage(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::OpenPageResponse>>(PrepareAsyncOpenPageRaw(context, request, cq));
    }
    // *
    // Query Page Status RPC.
    // Java sends PageStatusRequest to CEF.
    // CEF responds immediately with current PageStatusResponse.
    //
    // Used to poll current page load state synchronously.
    // Phase-7 TODO: Add polling mechanism for continuous updates.
    virtual ::grpc::Status PageStatus(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest& request, ::cefcontrol::PageStatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::PageStatusResponse>> AsyncPageStatus(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::PageStatusResponse>>(AsyncPageStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::PageStatusResponse>> PrepareAsyncPageStatus(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::PageStatusResponse>>(PrepareAsyncPageStatusRaw(context, request, cq));
    }
    // *
    // Shutdown RPC.
    // Java instructs CEF to terminate.
    //
    // Phase-7 TODO: Not required for MVP.
    virtual ::grpc::Status Shutdown(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest& request, ::cefcontrol::ShutdownResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::ShutdownResponse>> AsyncShutdown(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::ShutdownResponse>>(AsyncShutdownRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::ShutdownResponse>> PrepareAsyncShutdown(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::ShutdownResponse>>(PrepareAsyncShutdownRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // *
      // Handshake RPC.
      // CEF initiates this on connection.
      // Java validates and accepts/rejects the session.
      //
      // This MUST be the first RPC called by CEF.
      virtual void Handshake(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest* request, ::cefcontrol::HandshakeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Handshake(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest* request, ::cefcontrol::HandshakeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // *
      // Open Page RPC.
      // Java sends OpenPageRequest.
      // CEF responds immediately with OpenPageResponse (accepted or rejected).
      //
      // CEF then asynchronously sends PageStatusNotification messages
      // (via a separate callback mechanism or polling).
      //
      // Phase-7 TODO: Implement notification delivery (polling or push).
      virtual void OpenPage(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest* request, ::cefcontrol::OpenPageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void OpenPage(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest* request, ::cefcontrol::OpenPageResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // *
      // Query Page Status RPC.
      // Java sends PageStatusRequest to CEF.
      // CEF responds immediately with current PageStatusResponse.
      //
      // Used to poll current page load state synchronously.
      // Phase-7 TODO: Add polling mechanism for continuous updates.
      virtual void PageStatus(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest* request, ::cefcontrol::PageStatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PageStatus(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest* request, ::cefcontrol::PageStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // *
      // Shutdown RPC.
      // Java instructs CEF to terminate.
      //
      // Phase-7 TODO: Not required for MVP.
      virtual void Shutdown(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest* request, ::cefcontrol::ShutdownResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Shutdown(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest* request, ::cefcontrol::ShutdownResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::HandshakeResponse>* AsyncHandshakeRaw(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::HandshakeResponse>* PrepareAsyncHandshakeRaw(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::OpenPageResponse>* AsyncOpenPageRaw(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::OpenPageResponse>* PrepareAsyncOpenPageRaw(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::PageStatusResponse>* AsyncPageStatusRaw(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::PageStatusResponse>* PrepareAsyncPageStatusRaw(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::ShutdownResponse>* AsyncShutdownRaw(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cefcontrol::ShutdownResponse>* PrepareAsyncShutdownRaw(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Handshake(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest& request, ::cefcontrol::HandshakeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::HandshakeResponse>> AsyncHandshake(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::HandshakeResponse>>(AsyncHandshakeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::HandshakeResponse>> PrepareAsyncHandshake(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::HandshakeResponse>>(PrepareAsyncHandshakeRaw(context, request, cq));
    }
    ::grpc::Status OpenPage(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest& request, ::cefcontrol::OpenPageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::OpenPageResponse>> AsyncOpenPage(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::OpenPageResponse>>(AsyncOpenPageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::OpenPageResponse>> PrepareAsyncOpenPage(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::OpenPageResponse>>(PrepareAsyncOpenPageRaw(context, request, cq));
    }
    ::grpc::Status PageStatus(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest& request, ::cefcontrol::PageStatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::PageStatusResponse>> AsyncPageStatus(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::PageStatusResponse>>(AsyncPageStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::PageStatusResponse>> PrepareAsyncPageStatus(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::PageStatusResponse>>(PrepareAsyncPageStatusRaw(context, request, cq));
    }
    ::grpc::Status Shutdown(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest& request, ::cefcontrol::ShutdownResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::ShutdownResponse>> AsyncShutdown(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::ShutdownResponse>>(AsyncShutdownRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::ShutdownResponse>> PrepareAsyncShutdown(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cefcontrol::ShutdownResponse>>(PrepareAsyncShutdownRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Handshake(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest* request, ::cefcontrol::HandshakeResponse* response, std::function<void(::grpc::Status)>) override;
      void Handshake(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest* request, ::cefcontrol::HandshakeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void OpenPage(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest* request, ::cefcontrol::OpenPageResponse* response, std::function<void(::grpc::Status)>) override;
      void OpenPage(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest* request, ::cefcontrol::OpenPageResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void PageStatus(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest* request, ::cefcontrol::PageStatusResponse* response, std::function<void(::grpc::Status)>) override;
      void PageStatus(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest* request, ::cefcontrol::PageStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Shutdown(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest* request, ::cefcontrol::ShutdownResponse* response, std::function<void(::grpc::Status)>) override;
      void Shutdown(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest* request, ::cefcontrol::ShutdownResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::cefcontrol::HandshakeResponse>* AsyncHandshakeRaw(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cefcontrol::HandshakeResponse>* PrepareAsyncHandshakeRaw(::grpc::ClientContext* context, const ::cefcontrol::HandshakeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cefcontrol::OpenPageResponse>* AsyncOpenPageRaw(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cefcontrol::OpenPageResponse>* PrepareAsyncOpenPageRaw(::grpc::ClientContext* context, const ::cefcontrol::OpenPageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cefcontrol::PageStatusResponse>* AsyncPageStatusRaw(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cefcontrol::PageStatusResponse>* PrepareAsyncPageStatusRaw(::grpc::ClientContext* context, const ::cefcontrol::PageStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cefcontrol::ShutdownResponse>* AsyncShutdownRaw(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cefcontrol::ShutdownResponse>* PrepareAsyncShutdownRaw(::grpc::ClientContext* context, const ::cefcontrol::ShutdownRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Handshake_;
    const ::grpc::internal::RpcMethod rpcmethod_OpenPage_;
    const ::grpc::internal::RpcMethod rpcmethod_PageStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_Shutdown_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // *
    // Handshake RPC.
    // CEF initiates this on connection.
    // Java validates and accepts/rejects the session.
    //
    // This MUST be the first RPC called by CEF.
    virtual ::grpc::Status Handshake(::grpc::ServerContext* context, const ::cefcontrol::HandshakeRequest* request, ::cefcontrol::HandshakeResponse* response);
    // *
    // Open Page RPC.
    // Java sends OpenPageRequest.
    // CEF responds immediately with OpenPageResponse (accepted or rejected).
    //
    // CEF then asynchronously sends PageStatusNotification messages
    // (via a separate callback mechanism or polling).
    //
    // Phase-7 TODO: Implement notification delivery (polling or push).
    virtual ::grpc::Status OpenPage(::grpc::ServerContext* context, const ::cefcontrol::OpenPageRequest* request, ::cefcontrol::OpenPageResponse* response);
    // *
    // Query Page Status RPC.
    // Java sends PageStatusRequest to CEF.
    // CEF responds immediately with current PageStatusResponse.
    //
    // Used to poll current page load state synchronously.
    // Phase-7 TODO: Add polling mechanism for continuous updates.
    virtual ::grpc::Status PageStatus(::grpc::ServerContext* context, const ::cefcontrol::PageStatusRequest* request, ::cefcontrol::PageStatusResponse* response);
    // *
    // Shutdown RPC.
    // Java instructs CEF to terminate.
    //
    // Phase-7 TODO: Not required for MVP.
    virtual ::grpc::Status Shutdown(::grpc::ServerContext* context, const ::cefcontrol::ShutdownRequest* request, ::cefcontrol::ShutdownResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Handshake : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Handshake() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Handshake() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handshake(::grpc::ServerContext* /*context*/, const ::cefcontrol::HandshakeRequest* /*request*/, ::cefcontrol::HandshakeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandshake(::grpc::ServerContext* context, ::cefcontrol::HandshakeRequest* request, ::grpc::ServerAsyncResponseWriter< ::cefcontrol::HandshakeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_OpenPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OpenPage() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_OpenPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenPage(::grpc::ServerContext* /*context*/, const ::cefcontrol::OpenPageRequest* /*request*/, ::cefcontrol::OpenPageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOpenPage(::grpc::ServerContext* context, ::cefcontrol::OpenPageRequest* request, ::grpc::ServerAsyncResponseWriter< ::cefcontrol::OpenPageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PageStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PageStatus() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_PageStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PageStatus(::grpc::ServerContext* /*context*/, const ::cefcontrol::PageStatusRequest* /*request*/, ::cefcontrol::PageStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPageStatus(::grpc::ServerContext* context, ::cefcontrol::PageStatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::cefcontrol::PageStatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Shutdown : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Shutdown() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Shutdown() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Shutdown(::grpc::ServerContext* /*context*/, const ::cefcontrol::ShutdownRequest* /*request*/, ::cefcontrol::ShutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestShutdown(::grpc::ServerContext* context, ::cefcontrol::ShutdownRequest* request, ::grpc::ServerAsyncResponseWriter< ::cefcontrol::ShutdownResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Handshake<WithAsyncMethod_OpenPage<WithAsyncMethod_PageStatus<WithAsyncMethod_Shutdown<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Handshake : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Handshake() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::cefcontrol::HandshakeRequest, ::cefcontrol::HandshakeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::cefcontrol::HandshakeRequest* request, ::cefcontrol::HandshakeResponse* response) { return this->Handshake(context, request, response); }));}
    void SetMessageAllocatorFor_Handshake(
        ::grpc::MessageAllocator< ::cefcontrol::HandshakeRequest, ::cefcontrol::HandshakeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cefcontrol::HandshakeRequest, ::cefcontrol::HandshakeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Handshake() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handshake(::grpc::ServerContext* /*context*/, const ::cefcontrol::HandshakeRequest* /*request*/, ::cefcontrol::HandshakeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Handshake(
      ::grpc::CallbackServerContext* /*context*/, const ::cefcontrol::HandshakeRequest* /*request*/, ::cefcontrol::HandshakeResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_OpenPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OpenPage() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::cefcontrol::OpenPageRequest, ::cefcontrol::OpenPageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::cefcontrol::OpenPageRequest* request, ::cefcontrol::OpenPageResponse* response) { return this->OpenPage(context, request, response); }));}
    void SetMessageAllocatorFor_OpenPage(
        ::grpc::MessageAllocator< ::cefcontrol::OpenPageRequest, ::cefcontrol::OpenPageResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cefcontrol::OpenPageRequest, ::cefcontrol::OpenPageResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_OpenPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenPage(::grpc::ServerContext* /*context*/, const ::cefcontrol::OpenPageRequest* /*request*/, ::cefcontrol::OpenPageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OpenPage(
      ::grpc::CallbackServerContext* /*context*/, const ::cefcontrol::OpenPageRequest* /*request*/, ::cefcontrol::OpenPageResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PageStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PageStatus() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::cefcontrol::PageStatusRequest, ::cefcontrol::PageStatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::cefcontrol::PageStatusRequest* request, ::cefcontrol::PageStatusResponse* response) { return this->PageStatus(context, request, response); }));}
    void SetMessageAllocatorFor_PageStatus(
        ::grpc::MessageAllocator< ::cefcontrol::PageStatusRequest, ::cefcontrol::PageStatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cefcontrol::PageStatusRequest, ::cefcontrol::PageStatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PageStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PageStatus(::grpc::ServerContext* /*context*/, const ::cefcontrol::PageStatusRequest* /*request*/, ::cefcontrol::PageStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PageStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::cefcontrol::PageStatusRequest* /*request*/, ::cefcontrol::PageStatusResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Shutdown : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Shutdown() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::cefcontrol::ShutdownRequest, ::cefcontrol::ShutdownResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::cefcontrol::ShutdownRequest* request, ::cefcontrol::ShutdownResponse* response) { return this->Shutdown(context, request, response); }));}
    void SetMessageAllocatorFor_Shutdown(
        ::grpc::MessageAllocator< ::cefcontrol::ShutdownRequest, ::cefcontrol::ShutdownResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cefcontrol::ShutdownRequest, ::cefcontrol::ShutdownResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Shutdown() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Shutdown(::grpc::ServerContext* /*context*/, const ::cefcontrol::ShutdownRequest* /*request*/, ::cefcontrol::ShutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Shutdown(
      ::grpc::CallbackServerContext* /*context*/, const ::cefcontrol::ShutdownRequest* /*request*/, ::cefcontrol::ShutdownResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Handshake<WithCallbackMethod_OpenPage<WithCallbackMethod_PageStatus<WithCallbackMethod_Shutdown<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Handshake : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Handshake() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Handshake() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handshake(::grpc::ServerContext* /*context*/, const ::cefcontrol::HandshakeRequest* /*request*/, ::cefcontrol::HandshakeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_OpenPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OpenPage() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_OpenPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenPage(::grpc::ServerContext* /*context*/, const ::cefcontrol::OpenPageRequest* /*request*/, ::cefcontrol::OpenPageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PageStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PageStatus() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_PageStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PageStatus(::grpc::ServerContext* /*context*/, const ::cefcontrol::PageStatusRequest* /*request*/, ::cefcontrol::PageStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Shutdown : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Shutdown() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Shutdown() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Shutdown(::grpc::ServerContext* /*context*/, const ::cefcontrol::ShutdownRequest* /*request*/, ::cefcontrol::ShutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Handshake : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Handshake() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Handshake() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handshake(::grpc::ServerContext* /*context*/, const ::cefcontrol::HandshakeRequest* /*request*/, ::cefcontrol::HandshakeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandshake(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_OpenPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OpenPage() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_OpenPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenPage(::grpc::ServerContext* /*context*/, const ::cefcontrol::OpenPageRequest* /*request*/, ::cefcontrol::OpenPageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOpenPage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PageStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PageStatus() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_PageStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PageStatus(::grpc::ServerContext* /*context*/, const ::cefcontrol::PageStatusRequest* /*request*/, ::cefcontrol::PageStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPageStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Shutdown : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Shutdown() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_Shutdown() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Shutdown(::grpc::ServerContext* /*context*/, const ::cefcontrol::ShutdownRequest* /*request*/, ::cefcontrol::ShutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestShutdown(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Handshake : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Handshake() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Handshake(context, request, response); }));
    }
    ~WithRawCallbackMethod_Handshake() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handshake(::grpc::ServerContext* /*context*/, const ::cefcontrol::HandshakeRequest* /*request*/, ::cefcontrol::HandshakeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Handshake(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OpenPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OpenPage() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->OpenPage(context, request, response); }));
    }
    ~WithRawCallbackMethod_OpenPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenPage(::grpc::ServerContext* /*context*/, const ::cefcontrol::OpenPageRequest* /*request*/, ::cefcontrol::OpenPageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OpenPage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PageStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PageStatus() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PageStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_PageStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PageStatus(::grpc::ServerContext* /*context*/, const ::cefcontrol::PageStatusRequest* /*request*/, ::cefcontrol::PageStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PageStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Shutdown : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Shutdown() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Shutdown(context, request, response); }));
    }
    ~WithRawCallbackMethod_Shutdown() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Shutdown(::grpc::ServerContext* /*context*/, const ::cefcontrol::ShutdownRequest* /*request*/, ::cefcontrol::ShutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Shutdown(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Handshake : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Handshake() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cefcontrol::HandshakeRequest, ::cefcontrol::HandshakeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cefcontrol::HandshakeRequest, ::cefcontrol::HandshakeResponse>* streamer) {
                       return this->StreamedHandshake(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Handshake() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Handshake(::grpc::ServerContext* /*context*/, const ::cefcontrol::HandshakeRequest* /*request*/, ::cefcontrol::HandshakeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHandshake(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cefcontrol::HandshakeRequest,::cefcontrol::HandshakeResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OpenPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_OpenPage() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cefcontrol::OpenPageRequest, ::cefcontrol::OpenPageResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cefcontrol::OpenPageRequest, ::cefcontrol::OpenPageResponse>* streamer) {
                       return this->StreamedOpenPage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_OpenPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OpenPage(::grpc::ServerContext* /*context*/, const ::cefcontrol::OpenPageRequest* /*request*/, ::cefcontrol::OpenPageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOpenPage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cefcontrol::OpenPageRequest,::cefcontrol::OpenPageResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PageStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PageStatus() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cefcontrol::PageStatusRequest, ::cefcontrol::PageStatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cefcontrol::PageStatusRequest, ::cefcontrol::PageStatusResponse>* streamer) {
                       return this->StreamedPageStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PageStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PageStatus(::grpc::ServerContext* /*context*/, const ::cefcontrol::PageStatusRequest* /*request*/, ::cefcontrol::PageStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPageStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cefcontrol::PageStatusRequest,::cefcontrol::PageStatusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Shutdown : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Shutdown() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cefcontrol::ShutdownRequest, ::cefcontrol::ShutdownResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cefcontrol::ShutdownRequest, ::cefcontrol::ShutdownResponse>* streamer) {
                       return this->StreamedShutdown(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Shutdown() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Shutdown(::grpc::ServerContext* /*context*/, const ::cefcontrol::ShutdownRequest* /*request*/, ::cefcontrol::ShutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedShutdown(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cefcontrol::ShutdownRequest,::cefcontrol::ShutdownResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Handshake<WithStreamedUnaryMethod_OpenPage<WithStreamedUnaryMethod_PageStatus<WithStreamedUnaryMethod_Shutdown<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Handshake<WithStreamedUnaryMethod_OpenPage<WithStreamedUnaryMethod_PageStatus<WithStreamedUnaryMethod_Shutdown<Service > > > > StreamedService;
};

}  // namespace cefcontrol


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_cef_5fservice_2eproto__INCLUDED
